name: ai-sandbox
channels:
  - conda-forge
dependencies:
  - python=3.7
  - anndata
  - boto3
  - conda-pack
  - dask
  - dask-yarn
  - fabric
  - pandas
  - pyarrow
  - python-daemon
  - pyyaml
  - s3fs
  - tornado=5
  - xarray
  - zarr
